SignalK/n2k-signalk

n2kMappings.js
test/127488_engine_speed.js
test/127489_engine_params.js

linked to SignalK/specification pull request 153

added engine parameters mappings and tests

---

n2kMappings.js
test/127250_heading.js

The data was captured on a motor boat with a Raymarine plotter.

Add parsing for 127250 true heading

---

n2kMappings.js
test/128267_water_depth.js

Added surfaceToTransducer for depth 128267

Added surfaceToTransducer for depth pgn 128267

---

n2kMappings.js
test/127505_fluid_level.js

Add pgn 127505 fluid level

---

n2kMappings.js
test/65379_seatalk_pilot_mode.js

Not sure how to deal with these test failures

Added 65379 Seatalk: Pilot Mode

---

n2kMappings.js
test/65288_seatalk_alarm.js

Please review the test failures. I could not figure out how to validate the methods array.
One issue here is that I need to convert back to the Raymarine error codes so that I can send out the silence n2k command. I'd prefer to be able add some arbitrary data to the alarm, but instead I build the notification name with the Raymaine "Alarm Group"  and "Alarm ID"

Added 65288 Seatalk: Alarm

---

n2kMappings.js
test/128267_water_depth.js

Makes creating a depth notification alarm easier

Compute depth below surface

---

n2kMappings.js
test/65360_seatalk_pilot_locked_heading.js

Pending joachim's schema changes

Updated 65360 Seatalk: Pilot Locked Heading to latest proposed spec

---

n2kMappings.js
test/65345_seatalk_pilot_wind.js

Will require my pull request to specification to pass the tests

Added 65345 Seatalk: Pilot Wind Datum

---

n2kMappings.js
test/65288_seatalk_alarm.js

Raymarine alarm update

---

pgns/127505.js
pgns/130311.js
test/127505_fluid_level.js

tank level has the unit ratio ( 0 to 1) but was used as percentage ( 0
to100 )

fix: percent to ratio

---

pgns/129029.js
test/129029_position_data.js

Position data may be missing, so check that the input is
there with filter property.

fix: do not emit empty position pgn 129029

---

package.json

chore(package): update @signalk/signalk-schema to version 1.0.1

---

pgns/127489.js
test/127489_engine_params.js

Code was incorrectly multiplying by 1000

fix: incorrect conversion of oil pressure for pgn 127489

---

pgns/128259.js
test/128259_speed.js

 fix: missing navigation.speedThroughWater when the value is zero

---

pgns/129283.js
test/129283_xte.js

Add a test and fix the code to make sure we do not crash when state is undefined.

fix: 129283 should not throw exception when state is undefined

---

pgns/127488.js
pgns/127489.js
test/127488_engine_speed.js
test/127488_engine_trim.js
test/127489_engine_params.js
utils.js

fix: engine instances numbers above 1 show as starboard

---

fusion/130820.js

This has a bad `node` funcion and does not make sense to be in SignalK anyway

fix: remove bad menus entry

---

pgns/130312.js
test/130310-2.json

The baitWell source was showing up as undefined because it was looking for Temperature Instance but it is Instance in pgns.h.
Closes #168

fix: baitWell source

---

pgns/129038.js
test/129038_ais_class_a.js

See https://github.com/SignalK/signalk-parser-nmea0183/issues/165

feature: add specialManeuver indicator to 129038

---

pgns/129794.js
test/129794_ais_class_a_static_data.js

See https://github.com/SignalK/signalk-parser-nmea0183/issues/171

feature: add support for imo to AIS Class A Static (129794)

---

package.json

chore(package): update mocha to version 7.1.0

---

pgns/129038.js
pgns/129039.js
pgns/129040.js
pgns/129041.js
pgns/129793.js
pgns/129794.js
pgns/129798.js
pgns/129809.js
pgns/129810.js
pgns/130842.js

Closes https://github.com/SignalK/signalk-server/issues/1119

fix: exceptions with empty/missing AIS data

---

pgns/129038.js
pgns/129039.js
pgns/129040.js
pgns/129041.js
pgns/129793.js
pgns/129798.js
test/129038_ais_class_a.js
test/129039_ais_class_b.js
test/129040_class_b_extended.js
test/129793_ais_base_station_data.js
test/129794_ais_class_a_static_data.js
test/129798_sar.js
test/ais_utils.js

Feature: add sensors.ais.class to additional PGNs

---

pgns/130316.js
pgns/index.js
test/130310-2.json

Based on https://github.com/SignalK/n2k-signalk/pull/225.

feature: pgn 130316 exhaust temperature

---

pgns/130311.js
pgns/130313.js
pgns/index.js

Hi,
I found that the implementation PGN130313 is missing in SignalK. Herewith I would like to add the missing part to SignalK 
Regards
free-x

feature: add PGN 130313 Humidity, fix PGN 130311 output

---

pgns/129540.js
pgns/index.js
test/129540_sats_in_view.js

feature: pgn 129540 satellites in view

---

pgns/129794.js
test/129794_ais_class_a_static_data.js

fix: Ais destination should be string

---

pgns/index.js

feature: add PGNs 127403/4

---

pgns/129794.js
pgns/129810.js
test/129794_ais_class_a_static_data.js

Fixes https://github.com/SignalK/signalk-server/issues/1842.

fix: output callsignVhf with empty path
