pgns/127489.js, test/127489_engine_params.js
Instead of using rounded multiplier 0.0000028 for L/h -> m3/s conversion, divide by 3600000, which is algebraically more accurate, and may help avoid error accumulation elsewhere.
=> Fix for L/h -> m3/s unit conversion

package-lock.json, pgns/127489.js, test/127489_engine_params.js
Add the following (missing) fields to the test & parser for PGN 127489:
- Fuel Pressure
- Engine coolant pressure
- Total engine hours
- Engine oil temperature
Reference & related issue:
1. http://www.nmea.org/Assets/july%202010%20nmea2000_v1-301_app_b_pgn_field_list.pdf
2. https://github.com/SignalK/n2k-signalk/issues/117
=> Add missing fields to PGN 127489 parser

raymarine/65288.js, test/65288_seatalk_alarm.js
Raymarine has added a new alarm type which is not included in canboat.
=> fix: exception when an unknown raymarine alarm is received

pgns/130310.js, test/130310-2.json
Hi,
this PR extends PGN130310. This PGN is also used to transmit the information about water temperature. It has also been successfully tested (see http://www.cruisersforum.com/forums/f134/water-temp-in-ocpn-via-signalk-207730.html#post2726526).
Greeting
free-x
=> Extend pgn 130310 for water temperature

pgns/127488.js, pgns/127489.js, pgns/127506.js, pgns/127508.js, pgns/130312.js, pgns/130314.js, test/127488_engine_speed.js, test/127489_engine_params.js, test/127506_dc_detailed_status.js, test/127508_battery_voltage.js, test/130310-2.json, test/130314_pressure.js, utils.js
canboat has some changes to key names, like 'DC Instance' was changed to 'Instance'.
Since there's not versioning, this change makes to we can support the old and new keys.
=> fix: support changes to some key names in canboat

pgns/129025.js, test/129025_position.js
When the position 'rapid update' pgn is received, it may not contain a
valid latitude/longitude. When that happens, we should still generate
valid SignalK.
Before this fix, we would generate `"value":{"longitude":null,"latitude":null}}` which is invalid.
=> fix: bug parsing PGN 129025 without position data

lowrance/65285.js, pgns/130311.js, pgns/130312.js, temperatureMappings.js, test/130310-2.json, test/13031_temperature.js, test/65285_temperature.js
Update the test to read `temperatureMappings.js` and check that all the
values lead to valid SignalK data model.
Two NMEA2000 (liveWell and baitWell temperature) do not have a SignalK
mapping as of spec v1.0.4 so they are ignored for now.
=> test: fix tests for 13031x temperature

n2kMapper.js
the Z was missing from the timestamps that are generated from
strings in the analyzer json output
=> fix: generate UTC timestamps with Z

pgns/130311.js, test/130310-2.json
Conversion to Pascals seems to be off, see https://github.com/SignalK/signalk-server-node/issues/670.
=> fix: 130311 atmospheric pressure

temperatureMappings.js
Looks like there was a duplicate in `temperatureMappings.js` of
```javascript
'Heat Index Temperature': {
path: 'environment.outside.heatIndexTemperature'
},
```
so I removed one of them.
=> style: Remove duplicate Heat Index Temp

pgns/126983.js, pgns/126985.js, pgns/index.js, test/126983_alert.js, test/126985_alert_text.js
NMEA has standardized PGNs to handle alerts. The main alert
is handled in 126983 with the alert text handled in 126985.
The alert is sent ~1/sec with the alert text sent ~1/10 sec
or possibly longer. Because the notifications schema only allows
for a single value, we wait until we have data from both PGNs
before we process the update and create the notification.
=> feature: adds support for alert PGNs 126983 and 126985

pgns/130312.js, test/130310-2.json, test/13031_temperature.js
This adds support for those temperature sources not specifically defined by NMEA.
NMEA allows for a user defined temperature source ranging from 129-252.
The new path will be generic.temperatures.userDefined<###>.<instance>.temperature
The test has been added but will fail until generic is added to the specification.
=> feature: adds support for user defined temperatures

maretron/totalEnergy.js
Removes the conversion of totalEnergy values to joules as the values are already converted from kWh to joules in canboatjs.
=> fix: removes conversion of totalEnergy to joules

pgns/130306.js, test/130306_wind_data.js
There is not directionGround in the current SK spec. Instead
there are directionTrue and directionMagnetic. Note that True
refers here to same thing as in heading: what the number is
referenced from. Both direction paths are relative to Ground.
=> fix: 130306 direction output

pgns/130312.js
I'm not certain when this changed but the PGN field Source is now an int
instead of string. We are trying to replace the sourc with the instance
but that now throws an error "TypeError: n2k.fields.Source.replace is not a function".
This fix converts the Source int to string so that it can be replaced.
Example data
{"canId":368904234,"prio":5,"src":42,"dst":255,"pgn":130312,"time":"21:04:58.247","input":["21:04:58.247 R 15FD082A 7B 00 83 30 71 FF FF FF"],"fields":{"SID":123,"Instance":0,"Source":131,"Actual Temperature":289.76},"description":"Temperature","timestamp":"2022-04-08T21:04:58.402Z"}
=> fix: pgn 130312 userDefined temperature source handling

raymarine/126720.js, raymarine/65359.js, raymarine/index.js, test/126720_seatalk_STNG_pilot_mode.js, test/65359_seatalk_pilot_heading.js, test/65360_seatalk_pilot_locked_heading.js
Support for proprietary PGNs of Raymarine SeaTalk-STNG-Converter connected to Raymarine SeaTalk SmartPilot (S1, S2, S3) course computer with ST600X control heads.
I tried to filter 126720 as much as possible with PGN description "Seatalk1: Pilot Mode" and Manufacturer "Raymarine" to limit potential collision with other devices - such as FUSION radio and others.
65359 is the PGN SeaTalk converted Pilot Heading.,
=> feature: add support for Raymarine SeaTalk-STNG-Converter AP PGNs

.github/workflows/release_on_tag.yml, .github/workflows/require_pr_label.yml, package.json
Add GH Actions that ensure PRs are tagged for changelog and automation for creating releases from tags.
Remove previous method for creating releases.
=> chore: add release & changelog actions

n2kMapper.js, test/129038_ais_class_a.js
n2k-signalk is not expecting values to be zero length https://github.com/SignalK/signalk-server/blob/f800fc9c62b249dc9c7f67252339408b0d8fa304/packages/streams/n2k-signalk.js#L121-L122 so if the MMSI seems to be not ok return undefined, as any of the data in the delta don't make any sense with a questionable MMSI.
This will fix the stacktraces produced by data in the server n2k sample file related to #253
=> fix: bad MMSI handling

pgns/130306.js, test/130306_wind_data.js
I don't know if this is better handled by a quirks layer in SignalK that lets you work around particular instruments?
But this change is necessary on our yacht to correctly parse Wind data from a Digital  Yacht WND100 feeding NMEA0183 into a Cetrek 2900 which transmits NMEA2000 (marketed as CAN bus, not NMEA2000, but they seem to follow NMEA2000).
Probably not much Cetrek equipment out there these days, I think they stopped making it around 2010. But it's what we've got on board...
=> Support Cetrek 2900 wind data (without defined Reference)

pgns/127501.js, pgns/127503.js, pgns/127504.js
Both PGNs (127503 and 127504) have repeatable fields. canboatjs2 and canboat4 messages have
an array in fields called 'list' for these repeated dataset. This wasn't handled correctly by the current version of 127503.js and 127504.js
In my fix the PGNs now export directly a function to generate the deltas. I don't think this is the most
elegant solution, but since the number of lines is variable I couldn't figure out another way.
Unfortunately I have only one AC phase on my boat, it would be good to see real world data using
three phases. I could only simulate it by adding additional lines:
{"canId":435293963,"prio":6,"src":11,"dst":255,"pgn":127503,"timestamp":"2023-11-10T16:16:38.535Z","input":["  can0  19F20F0B   [8]  80 14 00 01 FC C0 58 0F","  can0  19F20F0B   [8]  81 00 88 13 FE FF …
=> fix: PGN 127503/127504 -> use new canboatjs2 / canboat4 data, PGN 127501 -> off by one error fixed

.github/workflows/test.yml
Drop Node.js versions below 18 from support by no longer running automated tests on them. Most code & pgns may still work, but is no longer supported by tests.
=> chore: drop support for Node.js below 18

pgns/127489.js
Normal state should have method array as empty, because it should not result in anything visual or audible.
=> fix: remove visual method from 127489 normal state

n2kMapper.js
n2k-signalk: address 0 changed from c0328700227b5a77 c0509b002270da77 TypeError: Cannot set properties of undefined (setting '60928')
at N2kMapper.toDelta
(/usr/local/lib/node_modules/signalk-server/node_modules/@signalk/n2k-signalk/n2kMapper.js:140:51)
at ToSignalK._transform
(/usr/local/lib/node_modules/signalk-server/node_modules/@signalk/streams/n2k-signalk.js:113:34)
at Transform._write
(node:internal/streams/transform:175:8)
at writeOrBuffer
(node:internal/streams/writable:392:12)
at _write
(node:internal/streams/writable:333:10)
at Writable.write
(node:internal/streams/writable:337:10)
at CanboatJs.ondata
(node:internal/streams/readable:809:22)
at CanboatJs.emit
(node:events:517:28)
at addChunk
(node:internal/streams/readable:368:12)
at readableAddChunk …
=> fix: an error is thrown when when a devices src id changes
